/* Header for module mathlib, generated by p2c */
#ifndef MATHLIB_H
#define MATHLIB_H


#ifdef MATHLIB_G
# define vextern
#else
# define vextern extern
#endif
/*elliptic integral of the second kind*/
extern double ELIP2 PP((double k));
/*elliptic integral of the first kind*/
extern double ELIP1 PP((double Ax));
extern double sinh_ PP((double x));
extern double cosh_ PP((double x));
extern double tanh_ PP((double x));
extern double asinh PP((double x));
extern double acosh PP((double x));
extern double atanh PP((double x));
extern double coth PP((double x));
extern double sech PP((double x));
extern double csch PP((double x));

extern double power PP((double x, double y));


#undef vextern

#endif /*MATHLIB_H*/

/* End. */
