/* Header for module Stripsubs, generated by p2c */
/*
$Header$

$Log$
Revision 1.2  2000/06/21 18:05:48  mikef
*** empty log message ***

Revision 1.5  1999/12/13 22:51:13  mikef
Add header and log keywords to all files

*/
#ifndef STRIPSUBS_H
#define STRIPSUBS_H


#ifndef MATHLIB_H
#include "mathlib.h"
#endif


#ifdef STRIPSUBS_G
# define GLOBAL
#else
# define GLOBAL extern
#endif

GLOBAL Void CPW_Z PP((double h, double Er, double w_strip,
		      double d_to_gplanes, double gplane_width, int finite,
		      double *Zo, double *Eeff));
GLOBAL Void ACPW_Z PP((double h, double Er, double b, double d1, double d2,
		       double *Zo, double *Eeff));
GLOBAL Void GCPW_Z PP((double h, double Er, double w, double d, double *Zo,
		       double *Eeff));
GLOBAL Void MSTP_Z PP((double h, double Er, double w, double *Zo,
		       double *Eeff));

GLOBAL Void BMSTP_Z PP((double h, double Er, double w, double b, double *Zo,
		       double *Eeff));


GLOBAL Void SLT_Z PP((double h, double Er, double w, double f, double *Zo,
		      double *Eeff, int *Error_ret));

GLOBAL Void STPLN_Z PP((double b, double Er, double w, double *Zo, double *Eeff));

GLOBAL Void OSTPLN_Z PP((double b, double Er, double w, double h, double *Zo, double *Eeff));


#define v_light         2.99792458e+8   /*m/s*/
#define Eo              8.854187818e-12   /*F/m*/
#define MAXERR          0.0001
#define Pi              3.14159265358979232646e+00
#define No              (120*Pi) /* ohms */


typedef enum {
  Microstrip, BuriedMicrostrip, GCPW, ACPW, CPW, Slotline, Stripline, OffsetStripline
} linetype;
typedef enum {
  backward, forward
} calctype;
typedef double input_vector[20];
typedef double output_vector[5];


linetype current_line_type;
double w, d1, d2, d, Zo, height, Er, gw, Eeff, f, b;
Char Ans[133];
boolean Finite_calc, OK;
Char Letter_selection;
calctype calculation;
int target_parameter;
double target_value;
int variable_parameter;
input_vector dim_vector;
output_vector result_vector;
boolean loop, debug_mode;
int Calc_error;


#undef GLOBAL

#endif /*STRIPSUBS_H*/

/* End. */
