/* Header for module Stripsubs, generated by p2c */
#ifndef STRIPSUBS_H
#define STRIPSUBS_H


#ifndef MATHLIB_H
#include "mathlib.h"
#endif


#ifdef STRIPSUBS_G
# define vextern
#else
# define vextern extern
#endif
extern Void CPW_Z PP((double h, double Er, double w_strip,
		      double d_to_gplanes, double gplane_width, int finite,
		      double *Zo, double *Eeff));
extern Void ACPW_Z PP((double h, double Er, double b, double d1, double d2,
		       double *Zo, double *Eeff));
extern Void GCPW_Z PP((double h, double Er, double w, double d, double *Zo,
		       double *Eeff));
extern Void MSTP_Z PP((double h, double Er, double w, double *Zo,
		       double *Eeff));


extern Void SLT_Z PP((double h, double Er, double w, double f, double *Zo,
		      double *Eeff, int *Error_ret));


#undef vextern

#endif /*STRIPSUBS_H*/

/* End. */
